### ISSUE TITLE
Kafka security parameters configuration

### ISSUE THREAD

**Issue by ffazil** [kbastani/pinot-debezium-basic-example#2]
Hi @kbastani 

Not sure if this is right place to ask. Great example. Any example or documentation that you can point me to configure security parameters for Kafka. I use Kafka from Confluent Cloud. Thanks in advance.

**Comment by kbastani** [comment]
Hi @ffazil.

I'm not sure if this helps: https://docs.confluent.io/platform/current/connect/security.html#separate-principals
